name: Java CI with Gradle

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The name of the library artifact'
        default: 'library'
        required: false
        type: string
      version:
        description: 'The version of the library'
        default: '0.0.1-SNAPSHOT'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      env:
        CI_RELEASE_VERSION: ${{ inputs.version }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: ${{ inputs.artifact-name }}
        path: build/libs/*.jar
        if-no-files-found: error

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
