name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.tag-processing.outputs.version }}
    steps:
    - name: Strip tag prefix
      id: tag-processing
      run: |
        TAG=${GITHUB_REF##*/}
        echo "version=${TAG#v}"
        echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"

  build:
    permissions:
      contents: write
    needs: version
    uses: ./.github/workflows/gradle.yml
    with: 
      version: ${{ needs.version.outputs.version }}
      artifact-name: library

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [version, build]
    steps:
    - name: Download built artifact
      uses: actions/download-artifact@v4
      with:
        name: library
    - name: Rename artifact
      run: |
        mv *.jar "${{ github.event.repository.name }}_${{ needs.version.outputs.version }}.jar"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ needs.version.outputs.version }}
        files: '*.jar'
